[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts =
    -v
    --strict-markers
    --tb=short
    --alluredir=allure-results
    --clean-alluredir
markers =
    smoke: критичный минимум, гоняется на каждый коммит
    regression: полный набор проверок
